node_name1:
  ros__parameters:
    param1: 30        # int
    param2: 3.3      # double
    param3: "string"    # string

node_name2:
  ros__parameters:
    param1: 3 # int
    param2: 3.3 # double
    param3: "str" # string

/**:
  ros__parameters:
    param1: 3 # int
    param2: 3.3 # double
    param3: "string" # string